### ISSUE TITLE
IDA 闪退

### ISSUE THREAD

**Issue by Cussrro** [WPeace-HcH/WPeChatGPT#10]
打开 .idb 文件 IDA 会闪退

**Comment by WPeace-HcH** [comment]
能提供具体信息吗？可以直接打开IDA查看output中有什么信息。

**Comment by Cussrro** [comment]
正常打开IDA output 没有信息，此时如果打开一个exe进行分析则插件正常，如果是打开 .idb 文件则会出现 
![image](https://user-images.githubusercontent.com/49461353/233889308-291e194c-aedc-4d6c-a2b6-8d3bc7318568.png)
然后卡主闪退

**Comment by WPeace-HcH** [comment]
有闪退错误的 IDB 方便发我邮箱看看吗？: )

**Comment by Cussrro** [comment]
链接：https://pan.baidu.com/s/10Y6Tf2QYeyNzMDm8kwyQQA 
提取码：g9br 
--来自百度网盘超级会员V2的分享

**Comment by WPeace-HcH** [comment]
我这边用 IDA7.7 是正常打开的，可以排查一下IDA的问题。 : )

**Comment by Cussrro** [comment]
orz 行
