### ISSUE TITLE
This model's maximum context length is 4097 tokens. However, your messages resulted in 181072 tokens. 

### ISSUE THREAD

**Issue by nmweizi** [WPeace-HcH/WPeChatGPT#11]
Auto-WPeGPT非常棒的功能，只是这个提示没法用啊。

**Comment by WPeace-HcH** [comment]
当前 Auto-WPeGPT 暂时只支持数据量较小的二进制文件，对于数据量大的文件会超出 API 最大 tokens，计划于下版本进行改进。
同时，对于大的二进制文件，虽然当前该功能不会产生GPT分析结果文档，但是会输出二进制的函数调用结构及可疑字符串供安全人员参考。: )
