### ISSUE TITLE
遇到了一些问题

### ISSUE THREAD

**Issue by zhefox** [WPeace-HcH/WPeChatGPT#15]
正在发送 ChatGPT-gpt-3.5-turbo API 请求，完成后将输出提示。@WPeace
Request to gpt-3.5-turbo sent...
OpenAI server could not complete the request: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

**Comment by WPeace-HcH** [comment]
请问使用 requirement.txt 安装了必要库吗？

**Comment by zhefox** [comment]
> 请问使用 requirement.txt 安装了必要库吗？

安装了，这个应该是因为openai的新版本和老版本的api改变有关系，可以试着更新一下，否则建议在requirement.txt中标识上openai的版本号openai==0.28，经过测试，该版本是可以正常运行的

**Comment by WPeace-HcH** [comment]
插件当前使用的都是新版API，requirement.txt 标识了版本号openai >= 0.27.0，正常来说应该是没有这个问题的。

**Comment by zhefox** [comment]
似乎不是最新版的API，因为默认给我安装的时候安装的是>1.0的最新版本，然后它提示我有些api已经不存在，已更换成xxx方法，然后我自行更换完之后他出现的这个提示，并告诉我可以选择降到0.28版本，更改版本后，确实不存在了该问题，可以关注一下最新的openai的api，或许可以解决你的疑惑

**Comment by WPeace-HcH** [comment]
抱歉，刚才没反应过来，插件使用的最新 IDA API。
你提到的 OpenAI API 的问题刚才看了下确实存在这个问题，非常感谢反馈！我将更新 requirement.txt 暂时解决该问题。
