### ISSUE TITLE
能否支持下定义openapi的反代url

### ISSUE THREAD

**Issue by xiaoccao** [WPeace-HcH/WPeChatGPT#16]
能否支持下定义openapi的反代url
比如说可以调用AZ的openai

**Comment by zhefox** [comment]
你改个openai.api_base=xxx代理url就行了

**Comment by WPeace-HcH** [comment]
你好，楼上给出的解决方式是正确的，你可以尝试添加此行来指定反代URL地址，如果有问题可以参考我最新更新到 WPeChatGPT.py 文件中的代码。
