### ISSUE TITLE
Some pitfalls I encountered

### ISSUE THREAD

**Issue by 0Ut5kWDaVQPfO** [WPeace-HcH/WPeChatGPT#19]
When using the ChatGPT API with a Chinese skin version

enable the proxy.
```
#proxies = {'https': "https://your api address/v1"}
#openai.proxy = proxies
```
this is error

 It needs to be changed like this:
```
openai.api_base = 'https://your api address/v1'
openai.api_key = 'sk-KxUG6zEFARt8CvsGsVryZz4nJ2xL3j1J9zcHQ1oVgZO28NYE'
```

**Comment by WPeace-HcH** [comment]
Hi, I don't quite understand your question, if you want to open the proxy separately when using WPeChatGPT (e.g. Clash), just change the 'proxies' parameters, the 'openai.api_base' parameters are provided for the reverse proxy URL (e.g. Azure).

**Comment by 0Ut5kWDaVQPfO** [comment]
What I mean is, due to the blockade on China, I couldn't get the gpt-3.5 API, so I had to use a domestic substitute API. This is how you need to set it up in order to use the substitute API properly.

**Comment by WPeace-HcH** [comment]
你好是的，我了解你的意思了，中国大陆需要反代URL或者代理，WPeChatGPT中如果设置反代URL的话是修改参数 'openai.api_base'，'proxies' 参数的作用是提供给VPN使用（例如clash默认监听本地端口7890，proxies参数可以指定走7890端口进行请求）。
