### ISSUE TITLE
module 'openai' has no attribute 'OpenAI'

### ISSUE THREAD

**Issue by happyfmy** [WPeace-HcH/WPeChatGPT#23]
File "E:/XXXXX/XXXX/IDA_Pro_7.7/plugins/WPeChatGPT.py", line 40, in <module>
    client = openai.OpenAI(api_key=openai_api_key)
             ^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'OpenAI'

**Comment by WPeace-HcH** [comment]
使用 "pip list" 检查openai包的版本，如果是旧版本请更新到最新包。（如果不想要更新的话可以下载旧版本WPeChatGPT <= v2.4）

**Comment by happyfmy** [comment]
openai 版本1.40.2

**Comment by happyfmy** [comment]
OpenAI server could not complete the request: Country, region, or territory not supported
换成了2.4版本，运行这个问题

**Comment by WPeace-HcH** [comment]
你好，我这边使用对应版本1.40.2无报错，可以尝试pip卸载openai包后重新install后再做尝试。
