### ISSUE TITLE
是否支持 azure GPT？

### ISSUE THREAD

**Issue by xbigwork** [WPeace-HcH/WPeChatGPT#25]
是否支持 azure GPT？怎么配置？

**Comment by WPeace-HcH** [comment]
你好，可以尝试使用反代URL，在插件代码修改 proxy_address 和 openai_api_key 参数：
openai_api_key = xxx
proxy_address=https://gpt-4-vision-resource.openai.azure.com/openai/deployments/gpt-4-vision/extensions

**Comment by xbigwork** [comment]
感谢回复，使用代码，可以实现：

from openai import AzureOpenAI

client = AzureOpenAI(
  azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"),
  api_key=os.getenv("AZURE_OPENAI_API_KEY"),
  api_version="2024-02-01"
)
