### ISSUE TITLE
找不到插件

### ISSUE THREAD

**Issue by likeSnake** [WPeace-HcH/WPeChatGPT#5]
作者你好，我放入plugins后重启IDA还是找不到插件
![QQ图片20230308150739](https://user-images.githubusercontent.com/86227653/223643999-2224501d-44f6-4344-b3a9-06d0e5f15bce.png)
![QQ图片20230308150758](https://user-images.githubusercontent.com/86227653/223644020-b4294522-5477-495d-824b-3e1ed6789659.png)

**Comment by likeSnake** [comment]
![QQ图片20230308150848](https://user-images.githubusercontent.com/86227653/223644283-8d5db10a-9e58-451e-9aff-f334051a1a8b.png)

**Comment by WPeace-HcH** [comment]
请确认是否按照 readme 安装 python 包，IDA 的输出界面可以查看插件的报错信息。
