### ISSUE TITLE
Not working on mac IDA pro 7.0 which is the last version in cracked on mac

### ISSUE THREAD

**Issue by xuuhaoo** [WPeace-HcH/WPeChatGPT#6]
我是mac版本的ida, 由于mac版本破解的ida最新版本仅支持7.0, 因此无法使用python3, 导致你的py报错, 这个有什么好的方案吗?

**Comment by WPeace-HcH** [comment]
建议通过升级 IDA 版本的办法解决（双系统安装高版本 IDA），WPeChatGPT 暂时没有支持 python2 的计划..
