### ISSUE TITLE
存在报错

### ISSUE THREAD

**Issue by mitiandashuaibi** [WPeace-HcH/WPeChatGPT#7]
正在发送 ChatGPT-gpt-3.5-turbo API 请求，完成后将输出提示。@WPeace
Request to gpt-3.5-turbo sent...
gpt-3.5-turbo could not complete the request: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000199BC393850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
使用的全局代理,然后浏览器也能正常访问gpt,求解决

**Comment by WPeace-HcH** [comment]
按照报错信息的话应该是代理配置问题，可以参考 readme 中**关于 OpenAI-API 报错**一节进行配置。
