### ISSUE TITLE
我的账户还有余额但是还是出现错误gpt-3.5-turbo could not complete the request: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by lrz2010** [WPeace-HcH/WPeChatGPT#9]
我的账户还有余额但是还是出现错误gpt-3.5-turbo could not complete the request: You exceeded your current quota, please check your plan and billing details.

**Comment by WPeace-HcH** [comment]
你好，可以参考 OpenAI 官方对此报错的解决方案：https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

**Comment by lrz2010** [comment]
试过了 API key我填上了 
![image](https://user-images.githubusercontent.com/44985031/231094025-b7045944-343c-4823-81a0-2ea8580aa428.png)
官网显示从未使用过 
![image](https://user-images.githubusercontent.com/44985031/231094141-2a7cd689-737d-48a4-8c9f-9114b2c72c8a.png)
客户端提示没有额度

**Comment by lrz2010** [comment]
![image](https://user-images.githubusercontent.com/44985031/231094313-98a5dec9-9fa5-439c-9e14-8e98ff3f88f0.png)
KEY 也正确填写了 我是前一阵的某天突然不好使的 我换过好几个KEY都不行 在哪之前还可以用的 前几天突然不好使的

**Comment by lrz2010** [comment]
![image](https://user-images.githubusercontent.com/44985031/231094751-c4545b2a-65d7-4cc2-94b1-7da24eade27d.png)
额度也是有的

**Comment by WPeace-HcH** [comment]
大概率是账户的问题，可以尝试注册另一个账号申请 API。

**Comment by WPeace-HcH** [comment]
这边确认了，是国内某些账号的 API 应该是被 OpenAI 冻结了，显示有余额但是无法使用，解决方法就是重新搞个账号 : )

**Comment by WPeace-HcH** [comment]
除此之外，免费的额度有三个月有效期，过期即使没有用完也会冻结。

**Comment by 13889703071** [comment]
可以使用转发的api吗

**Comment by WPeace-HcH** [comment]
转发API存在安全性和稳定性的风险，不做考虑。

**Comment by whyliuxing** [comment]
我刚开始也遇到了，充值也报错，通过在openapi的面板中修改Limits选项卡，重新修改下Limit 限制金额后好了
